# Generated by Django 2.0.2 on 2018-05-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
