# Generated by Django 2.0.2 on 2018-05-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180519_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='number',
        ),
    ]
